// angular/dashboard/src/modules/about/pages/about.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'rv-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent {}

<mat-grid-list cols="1">
  <mat-grid-tile colspan="1">
    <mat-card>
      <div>
        <h1>About</h1>
        <p>[Reasons I made this ish]</p>
        https://github.com/material-components/material-components-web-react
      </div>
    </mat-card>
  </mat-grid-tile>
</mat-grid-list>

// react/src/scenes/About/index.js
import React, { Component } from 'react';
import {Cell, Grid, Row} from '@material/react-layout-grid';


export default class About extends Component {
  render() {
    return (
      <Grid>
        <Row>
          <Cell columns={12}>
            <h1>About</h1>
            <p>[Reasons I made this ish]</p>
            https://github.com/material-components/material-components-web-react
          </Cell>
        </Row>
      </Grid>
    );
  }
}
